name: android_syntax_checker

on:
  push:
    branches:
      - master

jobs:

  syntax_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19.0.2'

      - name: Set executable permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --console=plain

      - name: Check Kotlin syntax
        run: ./gradlew ktlintCheck
